name: vlang-build

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: nocturlab/setup-vlang-action@v1
      with:
        v-version: latest
      id: v
    - name: Code Formatting
      run: v fmt -w vlang-udf.v
    - name: Build app
      run: v -o vlang-udf -prod .
    - name: Get Time
      if: github.event_name != 'pull_request'
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDDHHmmss'
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            vlang-udf
        tag_name: v${{ steps.time.outputs.time }}
        release_name: vlang-udf_${{ steps.time.outputs.time }}
        draft: false
        prerelease: false
        overwrite: true
